### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Milaine** [uyjulian/ControlPack#1]
Cmon bro, I love your mod and I cant live without it!
Sadly, you're behind the schedule most of the time which makes it hard to use it.
I'd appreciate it a hella lot if you updated the mod c:

**Comment by uyjulian** [comment]
I'll update it at an unspecified time (after I get my gradle conversion sorted out).
This isn't a bug report, so I'm close&locking. (use MinecraftForums for stuff other than bugreport)
