### ISSUE TITLE
You can turn all the features on and off ?

### ISSUE THREAD

**Issue by chneau** [uyjulian/ControlPack#11]
Can't find the menu in 1.12.2
Where is it supposed to be ? If I remenber in old versions you could access a menu from the main options.

Am I missing something or is it a conflict with other mods ?3

So far I use :
15/03/2018  22:19           263,258 Inventory-Tweaks-Mod-1.12.2.jar
15/03/2018  22:19           537,164 jei_1.12.2-4.8.5.147.jar
15/03/2018  22:21            63,802 mod-cp1.12.2-5.94.3-mc1.12.2.litemod
15/03/2018  22:21           611,798 mod_voxelMap_1.7.0_for_1.12.2.litemod
15/03/2018  22:32         2,334,134 OptiFine_1.12.2_HD_U_C9.jar

And it looks like the menu item is missing

Edit:

At least I found the config file which allowed me to change an option I wanted to modify: 

options.holdtoattack:true

**Comment by uyjulian** [comment]
Press Alt+C

**Comment by chneau** [comment]
Ha thanks, good to know :)
