### ISSUE TITLE
Update for 1.13.2 ?

### ISSUE THREAD

**Issue by BloodEko** [uyjulian/ControlPack#12]
Hey, seems like Liteloader is dead, but there is a new modloader called Rift.

Stuff like Voxelmap is now available for Rift too.
Might there be a chance you port this project to Rift and update for 1.13.2 ?

https://www.curseforge.com/minecraft/mc-mods/rift

**Comment by uyjulian** [comment]
I plan to update to the latest Minecraft version whenever I fix known bugs.

**Comment by 1337god** [comment]
> I plan to update to the latest Minecraft version whenever I fix known bugs.

Bless you, I always loved this mod, but didn't see it updated for a really long time.

**Comment by uyjulian** [comment]
> > I plan to update to the latest Minecraft version whenever I fix known bugs.
> 
> Bless you, I always loved this mod, but didn't see it updated for a really long time.

It's still in my to-do list.

**Comment by guekho64** [comment]
> 
> 
> Hey, seems like Liteloader is dead, but there is a new modloader called Rift.
> 
> Stuff like Voxelmap is now available for Rift too.
> Might there be a chance you port this project to Rift and update for 1.13.2 ?
> 
> https://www.curseforge.com/minecraft/mc-mods/rift

After seeing this (1 month late...) I was so shocked by that information that I directly went to investigate the topic: It seems, as @BloodEko has said, that _LiteLoader_ is really dead (Up to MInecraft 1.12), but also looking at their development branch of _LiteLoader_ I found builds of _*MixIn*_ , which is part of  _Rift ModLoader_.

Could that mean that _Rift ML_ is just the continuation of _LiteLoader ML_ ?
And if that's true, Could it mean also that porting from _LiteLoader_ to _Rift_ is theorically easy?

I dunno, but I also loved this mod back when 1.7.10 was the most popular Minecraft version. Using this mod, combined with some lost knowledge, I was able to login to a Minecraft Skyblock Server with multiple sessions at the same time (Bypassing IP filters), and I only had to move each character into an exact point, and activate the mod to let it do the hard work, like fishing, collecting snow, or just letting it stand there, to load a specific chunk (And let a mob spawner do its work)...

Such great times...

**Comment by uyjulian** [comment]
Rift is stuck at 1.13/1.13.2 while Fabric is for 1.14 and above.

Also, Fabric does not use MCP mappings, but mappings from "Yarn", its own system of mappings.
After I fix known bugs and reorganize the code, I'll start porting to Fabric and 1.14. However, it may take me a while to do that, as I am busy with other projects. I'm accepting patches if anyone wants to contribute.
