### ISSUE TITLE
Can not sprint

### ISSUE THREAD

**Issue by uyjulian** [uyjulian/ControlPack#3]
Issue: you can not sprint by double-tapping W.
Known cause: "toggle sprint" code overrides Minecraft.

**Comment by MauveCloud** [comment]
I don't remember whether double-tapping W worked with this mod in the 1.7.10 version, but at least the separate sprint key (defaults to Control) worked.  However, in the 1.10.2 version, that doesn't work.  ControlPack's "start sprinting" works, but provides no way to stop sprinting; thus when I'm standing still I get particle effects at my feet as if I'm running in place and tearing up the terrain.

**Comment by uyjulian** [comment]
The sprint is a toggle. That is, press ControlPack's sprint key once to enable sprint, then press it again to disable sprint.
However, I'm not doing the toggle correctly. I call a function which sets sprint to true every frame, so that is what is causing the particles to fly. I should call the function only when sprint is not active, which happens when, for example, you run into a wall.

**Comment by uyjulian** [comment]
Sprint function has been removed from this mod, because Minecraft comes with its own sprint function.
